# Generated by Django 6.0 on 2025-12-30 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medinova_app', '0002_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
