# Generated by Django 6.0 on 2026-01-03 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medinova_app', '0004_doctor_testimonial_blogs_description_blogs_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='content',
        ),
        migrations.AlterField(
            model_name='blogs',
            name='description',
            field=models.TextField(),
        ),
    ]
